--liquibase formatted sql

--changeset boyd.timmerman:1

create table items (
   id          integer generated by default on null as identity
,  blob        blob           not null
,  mime_type   varchar2(100)  not null
,  name        varchar2(100)  not null
,  description varchar2(2000)
,  price       number(6,2)         
,  labels      varchar2(2000)
,  flag        integer        default 0
,  created_by  varchar2(100)  not null
,  created_on  date           not null
,  updated_by  varchar2(100)  not null
,  updated_on  date           not null
);

--rollback: drop table items;